### ISSUE TITLE
Xamarin Android Exoplayer 2.8.8. 

### ISSUE THREAD

**Issue by haohighview** [martijn00/InteractiveMediaAdsXamarin#1] opened 2018-11-12 16:07 UTC
Can we update it to the latest version? In my binding project I use the latest version of sdk it works very well.
{Java.Lang.Reflect.InvocationTargetException: Exception of type 'Java.Lang.Reflect.InvocationTargetException' was thrown. ---> Java.Lang.IncompatibleClassChangeError: Found class com.google.ads.interactivemedia.v3.api.ImaSdkSettings, but interface was expected (declaration of 'com.google.ads.interactivemedia.v3.api.ImaSdkSettings' appears in /data/app/com.test.demo-1/base.apk:classes2.dex)
   --- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <034d4a9852dd45bea9353cc7776c99f0>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00014] in <034d4a9852dd45bea9353cc7776c99f0>:0 
  at Java.Lang.Reflect.Constructor.NewInstance (Java.Lang.Object[] initargs) [0x00029] in <a10f61e70eeb434e952fef884856c199>:0 
  at MvxStandardTemplate.Droid.ExoPlayer.ExoPlayerManager.CreateAdsMediaSource () [0x0006b] in E:\DataHaoZhang\TFSProjects\HMediaApp\MvxStandardTemplate\MvxStandardTemplate.Android\ExoPlayer\ExoPlayerManager.cs:197 
  --- End of managed Java.Lang.Reflect.InvocationTargetException stack trace ---
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
	at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:30)
	at android.view.View.performClick(View.java:5655)
	at android.view.View$PerformClick.run(View.java:22633)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:159)
	at android.app.ActivityThread.main(ActivityThread.java:6385)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
Caused by: java.lang.IncompatibleClassChangeError: Found class com.google.ads.interactivemedia.v3.api.ImaSdkSettings, but interface was expected (declaration of 'com.google.ads.interactivemedia.v3.api.ImaSdkSettings' appears in /data/app/com.tesst.demo-1/base.apk:classes2.dex)
	at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.<init>(ImaAdsLoader.java:380)
	at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.<init>(ImaAdsLoader.java:325)
	... 13 more
}

**Comment by martijn00** [comment] 2018-11-12 16:19
Duplicate of https://github.com/martijn00/ExoPlayerXamarin/issues/76

**Comment by martijn00** [comment] 2018-11-12 16:54
Fixed in https://github.com/martijn00/InteractiveMediaAdsXamarin/commit/e21db8745db067b87c9aadcd36da19f809bf3dee

**Closed as completed by martijn00** 2018-11-12 16:54 UTC
